version: '3.8'

services:
  mongo-prod:
    image: mongo:6.0
    container_name: po9avan-mongo-prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # Открываем порт для доступа с вашего IP
    ports:
      - "27017:27017"
    volumes:
      - mongo_prod_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_prod_data: