version: "3.9"

services:
  app:
    build: .
    container_name: po9avan-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/po9avan}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL:-http://localhost:3000/}
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: po9avan-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
